### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sheerlox** [insurgent-lab/javascript-lib-template#21]
- [ ] run tests on all branches (and checks deduplication)
- [ ] add `dev` branch as default branch, and set release config as `alpha` to allow development iterations
- [ ] setup Semantic Release authentication through a GitHub App and add instructions on adding it as an exception on the "no bypass" ruleset (to allow bypassing the required checks) [note: maybe add a "semantic-release bypass" instead]
- [ ] `.eslintrc`: [remove `ecmaVersion`, `env: { node: true }` and set `env: { es2017: true }`](https://github.com/eslint/eslint/issues/9109#issuecomment-322277627) + [minimum node version `>=10.8.0`](https://node.green/#ES2017) in `package.json`
- [ ] remove `.eslintrc.js` from ESLint `ignorePatterns`
- [ ] [add `.prettierignore`](https://github.com/talent-ideal/semantic-release-hex/commit/cdd8162efd2123eb225a6b4001de7d3348806c85)
- [ ] add [`knip`](https://github.com/webpro/knip) (see [sheerlox/import-from-esm](https://github.com/sheerlox/import-from-esm))
- [ ] add [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import)
- [ ] [ci(action): don't run tests on branches where the release runs](https://github.com/talent-ideal/semantic-release-hex/commit/6d6478fc1af41de802a74d65580d94b2f1d53460)

_Note: use [talent-ideal/semantic-release-hex](https://github.com/talent-ideal/semantic-release-hex/tree/dev) as a reference as most of these has already been done there._
